# Generated by Django 3.1.7 on 2021-04-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='session_token',
        ),
    ]
