# Generated by Django 3.1.7 on 2021-04-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210405_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adults',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='childrens',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
